### PR TITLE
Add modal functionality.

### PR DESCRIPTION
**Pull request by Zertroz**
This will impliment the modal functionality for the full recipe display. Clicking on a recipe will open a window that gives you the name, image, ingredients list and cost, and the instructions. CSS styling is still required.

### CODE REVIEW

**Comment by Zertroz** [comment]
For changes, check lines 37-51 on index.html, the showFull() function on scripts.js, and the modal section (bottom of page) on styles.css

**Review by LeftyLincoln — APPROVED** [review]
MicroModal for the win, this is super neat. We will tighten it up.

**Comment by Jesusborjas006** [comment]
MicroModal is a nice feature!

**Review by LSeward0421 — APPROVED** [review]
Looks great! We just need to make pretty now. :)

**Pull request merged**
